
spring.datasource.url: jdbc:mysql://localhost:3306/springsecurity?serverTimezone=UTC
spring.datasource.username: admin
spring.datasource.password: admin
spring.jpa.hibernate.ddl-auto: update
spring.jpa.hibernate.namin-strategy: org.hibernate.cfg.ImprovedNamingStrategy
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect